### ISSUE TITLE
v0.1

### ISSUE THREAD

**Issue by donmccurdy** [donmccurdy/greendoc#2]
**MVP:**

- [x] populate OG tags
- [x] exhaustive warnings on broken links
- [x] support category tag in export listing
- [x] support class hierarchies
- [x] support standalone MD pages
- [x] hide external sources in export listing (Graph, GraphEdge)
- [x] hide items marked `@hidden`
- [x] clean up URLs: `modules/x/classes/y.html`
- [x] support enums
- [x] populate JSDoc links
- [x] support inherited members
- [x] remove _2 suffixes
- [x] support functions

**Stretch:**

- [ ] support 'inline' types (define options below function, and defaults?) #27
- [ ] support constants, type aliases, etc. #26
- [ ] support multiple signatures (see DenoIO) #25
- [ ] populate JSDoc tags #20 
- [ ] support inherited filter #28

**Comment by donmccurdy** [comment]
Moved stretch goals to new issues. Closing.
